wordpress:
        image: wordpress
        links: 
                - wordpress_db:mysql
        ports:
                - 8080:80
wordpress_db: 
        image: mariadb
        environment: 
                MYSQL_ROOT_PASSWORD: qwerty
phpmyadmin: 
        image: corbinu/docker-phpmyadmin
        links: 
                - wordpress_db:mysql
        ports:
                - 8000:80
        environment:
                MYSQL_USERNAME: root
                MYSQL_ROOT_PASSWORD: qwerty
